spring:
  application:
    name: fiap-videoframe
  data:
    mongodb:
      uri: ${MONGO_DB_URI}
#      password: "fiap#2025"
#      username: "videoStream"
#      host: 172.17.108.191
#      port: 27017
#      database: videoframe
  cloud:
    aws:
      sqs:
        endpoint: ${application.aws.endpoint-override}
        region: ${application.aws.region-override}

application:
  broker:
    from: ${AWS_SQS_QUEUE_NAME}
  aws:
    region-override: ${AWS_REGION}
    endpoint-override: ${AWS_SQS_ENDPOINT}

logging:
  level:
    br.com.fiap.challenge.videoframe: DEBUG