server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: fiap-videoframe
  data:
    mongodb:
      uri: ${MONGO_DB_URI}
  cloud:
    aws:
      sqs:
        endpoint: ${application.aws.endpoint-override}
        region: ${application.aws.region-override}

application:
  broker:
    from: ${AWS_SQS_QUEUE_NAME}
  aws:
    region-override: ${AWS_REGION}
    endpoint-override: ${AWS_SQS_ENDPOINT}

logging:
  level:
    br.com.fiap.challenge.videoframe: DEBUG

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    endpoint:
      health:
        probes:
          enabled: true
        show-details: always
  endpoints:
    web:
      exposure:
        include: health