apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-video-backoffice-deployment
  labels:
    app: eks-video-backoffice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-video-backoffice-app
  template:
    metadata:
      labels:
        app: eks-video-backoffice-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: eks-video-backoffice-app
          image: 345124661122.dkr.ecr.us-east-1.amazonaws.com/video-backoffice:latest
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: MONGO_DB_URI
              value: "mongodb+srv://felipebarras:felipe2711@ms-video-processor.suwbuz3.mongodb.net/test?retryWrites=true&w=majority&appName=MS-VIDEO-PROCESSOR"
            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_SQS_ENDPOINT
              value: "https://sqs.us-east-1.amazonaws.com/345124661122/SQS-FIAP-Hackathon"
            - name: AWS_SQS_QUEUE_NAME
              value: "SQS-FIAP-Hackathon"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              cpu: 2000m
              memory: 2048Mi
          imagePullPolicy: IfNotPresent
      serviceAccountName: eks-video-backoffice-sa
      nodeSelector:
        kubernetes.io/os: linux