apiVersion: v1
kind: Secret
metadata:
  name: eks-video-backoffice-secrets
  labels:
    app: eks-video-backoffice-app
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QVNJQVZBV1lJTTZCSjdaS0ozS0I=
  AWS_SECRET_ACCESS_KEY: czh0cnY4RUdjZXdXS2pBeE1sUVZ2bFBiS3lRb05iSTljVzVSVm5HZw==
  AWS_SESSION_TOKEN: SVFvSmIzSnBaMmx1WDJWakVGd2FDWFZ6TFhkbGMzUXRNaUpITUVVQ0lRRHN5c1VOQURrc05kN1d5SFBxZVUrOHlmbU05VS9OY1dBanhRQnQ5T3MzcEFJZ2NybG5nVjE4TjhPR2hNZ00wckxnU3dSNEFLYkExWFFTZ3h2Q3p6cDN5a01xdkFJSTVmLy8vLy8vLy8vL0FSQUFHZ3d6TkRVeE1qUTJOakV4TWpJaURHU0tlclJsOW5CVHRMR2QraXFRQXRlRGZYdUMwYTJIVXVONlB5KzNadmZ0UFp6RElmSk5MbFc0NWlqa1ptc3FXZktQb0JTRWtKM1hEbGZWbmNEd1hzKzAzY3BmTmU3dk1hYk4xVlplN2F0ZmhRZDk4NDF0Rkk1T2tjTXY2bHZEcmcrV0dXdTcvUnVPZFdId1M4VVpSOHRkekFMM0owbWxZUWhselRRellnRTg3RFVrZ2F3Y0hKODN1a0FkdWRkTG5sL2hBTlFnNTlzaHZKenZMY3ZKSXRwQjZOWTFBY21BalFsMkVENTdJVnM1SXpQTkdWYk92eWllQWNQMUtIU3pjYndRN29COVpBcVVRMDJwWWtiOG4rcVFQUmlvK29taW5JdmE3cHBrc0JPdU5scVBIZmhJMFEvZ2ZjWHBMUlRqd3V6SGdPMkVKR1JWemRMaVpGYXdjd0JXWVFxSzAvN05scXV0OWJwb2lnWTF2U2FGUmoyMG5iTHlEVmtnaVBiRE1OL0xvY0FHT3AwQmFWTGtVVk80ZXlmdE5aRDcra28yK3k1LzdUSnFNMG1TSzRrelRiTEFNa0E5cjVaS1QxSkpRSFN4alN5b3VSTXVNTGpKRXNia0JreWVHbEs2N1M2QmJvOHB4aWxja1RmRWdmM3BsVUVsMHI3S05UaXNzcXRZQUlYOGRDQWh6Q1ZxMGxyOGZDRlpsc2dDYWZRWTljTFY2TTZKS1FaRXhXVXIvKzEycDBkdzltdGdtc3BPd1F0OU5paDFaZWptUU5rdUJoMUZNVUEzcEV5YUh1TTJpZz09
