apiVersion: v1
kind: Secret
metadata:
  name: eks-video-backoffice-secrets
  labels:
    app: eks-video-backoffice-app
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QVNJQVZBV1lJTTZCQ0VEV1laUkQ=
  AWS_SECRET_ACCESS_KEY: MWZnVEdIejFyV2FZWmg1bGlrMnMzUXBzQjRoZEkrTnVNS25POGhxUg==
  AWS_SESSION_TOKEN: SVFvSmIzSnBaMmx1WDJWakVEd2FDWFZ6TFhkbGMzUXRNaUpITUVVQ0lEN1lNZEZXeHNWVDRLeHBEMklSRFJLWWVybXFuZkE2ME1sSmtWNGVhZFQ2QWlFQXRnVlBWWGRLLzcrZXdJcWtzcEVKOTRsNnBlTW5HMW05K3ZIWWJtN0c0ckVxdkFJSXhmLy8vLy8vLy8vL0FSQUFHZ3d6TkRVeE1qUTJOakV4TWpJaURPRnpqU2NHSjEza01sdzJUU3FRQWpvYzhhNkc1Zzh5azJVYmYwYmJBemw5aU9oc1MyQnUrc0xGR08xQXg1NXpPSlNHbzA2NmlHS21Sc0VQMS9iVHl1NGw2TVpjTklvT2VyWVRhR29aUDJlektCTEZ3ZTRBREZPTjNla2FKQ3ZjQjhibDVnWk4rcnpSb1F4M1lhcnVRLzBiYmlnVUkrR0V4aEFwejNzRWdqdFdYbjQxUkM2OU52empBeVEzNjVHYUZTcnhBTTIydEc4Z3ZuT1RhMDAzOFdYak5LMTV5MDZnZ1NTSmRuTzhZK1dRMlNZMnNzYW1vb05lZXRzencxdW5idEdVR0t5M01pU2RzRWZJUnVtNGE1M0FEK2tUSmhpTTFYRFdkQTNHelFvMElSc3d2eGlYeGk5SHozeTNHMkFGVTUwTU9adXpiWDNwZzJ4eGs4dEtIREM0ZTlGZU84NU5HUTN4MlBha1ZnTUM2cnJ5YUhEUkNId01JekliV1hGZk1JeTdtc0FHT3AwQk8xdEdwYmU4bENtK2YwdjFhc3djTEJId3dTN1liOEpKd3JQc2llL0xNeHVDZXUweDBnMTlvTzdhV2lXbkpkUWNkTUFjUDZqYzZCRHNNam05emd6WldPV0xOQ0d2NmtDRlVTNEdqdHNHY1JsTXNIbG5vTEtrODA5VkxJWU9WTzltakJ4ZEszQm1KSW9hSCt4SG5kSmtpN0dwUWhHcnJHYkJPeExPVkJVYk8rR1o0bmYvMnpZTlE2dUdNL0thREJuQUF2MzkrQ2tSZVMzMnU0d1BGdz09
